INSERT INTO CARS
    (REG_NUMBER, YEAR_OF_MANUFACTURE, COLOUR, IS_TAXED)
VALUES ('ABC123', 2021, 'Red', true);

INSERT INTO CARS
    (REG_NUMBER, YEAR_OF_MANUFACTURE, COLOUR, IS_TAXED)
VALUES ('DEF456', 2022, 'Blue', false);

INSERT INTO CARS
    (REG_NUMBER, YEAR_OF_MANUFACTURE, COLOUR, IS_TAXED)
VALUES ('GHK789', 2023, 'Green', true);
